[package]
name = "virus-db"
version = "0.1.0"
authors = ["Matthew Piziak <matthew.piziak@gmail.com>"]

[dependencies]
hyper = "0.9.10"
rayon = "0.4.3"
rustc-serialize = "0.3"
select = "0.3.0"
time = "0.1"
